---
sudo      : required
language  : objective-c

matrix:
  include:
    - os        : osx
      osx_image : xcode9
      xcode_sdk : macosx10.13

    - os        : osx
      osx_image : xcode8.3
      xcode_sdk : macosx10.12

    - os        : osx
      osx_image : xcode8.2
      xcode_sdk : macosx10.12

    - os        : osx
      osx_image : xcode8.1
      xcode_sdk : macosx10.12

    - os        : osx
      osx_image : xcode8
      xcode_sdk : macosx10.11

    - os        : osx
      osx_image : xcode7.3
      xcode_sdk : macosx10.11

# Uninstall the existing Homebrew installation that TravisCI sets up
before_install:
  - 'ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)" -- -f'
  - sudo rm -rf /usr/local/Homebrew
  - sudo rm -rf /usr/local/Caskroom
  - sudo rm -rf /usr/local/bin/brew

# Install Ansible on the system using pip
install:
  - sudo easy_install pip
  - sudo pip install ansible

script:

  # Check our syntax before beginning
  - sudo ansible-playbook playbook.yml --syntax-check

  # Wait for 30 seconds and run the playbook
  - "sudo ansible-playbook --extra-vars '{\"sudoers\" : false}' playbook.yml"

  # Repeat the playbook to ensure that nothing changed (idempotence test)
  - DIFFTEST=$(mktemp)
  - "sudo ansible-playbook --extra-vars '{\"sudoers\": false}' playbook.yml | tee -a ${DIFFTEST}"
  - >
    cat ${DIFFTEST}
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence Passed' && exit)
    || (echo 'Idempotence Failed' && exit 1)
