---
sudo      : required
language  : objective-c

matrix:
  include:

    # High Sierra
    - os        : osx
      osx_image : xcode9.3beta
      xcode_sdk : macosx10.13


# Set our test profile
env:
  - MYMAC_PROFILE="${TRAVIS_BUILD_DIR}/profiles/test.yml"

# Uninstall the existing Homebrew installation that TravisCI sets up
before_install:
  - 'ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)" -- -f'
  - sudo rm -rf /usr/local/Homebrew
  - sudo rm -rf /usr/local/Caskroom
  - sudo rm -rf /usr/local/bin/brew

# Install Ansible on the system using pip
install:
  - sudo -H easy_install pip
  - sudo -H pip install --upgrade pip
  - sudo -H pip install --ignore-installed six --upgrade ansible

script:

  # Run Ansible-Galaxy installation
  - ansible-galaxy install -r requirements.yml

  # Check our syntax before beginning
  - ansible-playbook test.yml --syntax-check

  # Run the playbook to see if it gets to the end
  - ansible-playbook test.yml

  # Repeat the playbook to ensure that all changes were identified and skipped (idempotence test)
  - DIFFTEST=$(mktemp)
  - ansible-playbook test.yml | tee -a ${DIFFTEST}
  - >
    cat ${DIFFTEST}
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence Passed' && exit)
    || (echo 'Idempotence Failed' && exit 1)
