---
- hosts      : all
  connection : local

  roles:
    #- roliver.filevault
    - ansible-role-filevault

  # If a profile is provided, load it from the environment
  vars:
    mymac_profile : "{{ lookup('env', 'MYMAC_PROFILE')|default(omit) }}"


  # Run the profile
  tasks:

    ### PREP AND SETUP ###############################################################################################

    - name  : Setup
      block :

        # This variable stores module names that have been completed, to implement single-use patterns where needed
        - name     : Setting tracking variable
          set_fact:
            mymac  : []

        # Check that our sudo password is correct
        - name         : Checking sudo password
          become       : true
          shell        : /usr/bin/true
          changed_when : false


        # Ensure we are running on macOS
        - name  : Ensuring that this is being run on a MacOSX operating system
          fail:
            msg : "This installer is only supported by MacOSX, current operating system is \"{{ ansible_distribution }}\""
          when  : ansible_distribution != "MacOSX"


        # Helper tasks that provide shared functionality for modules
        - name          : Finding `sed` path
          include_tasks : tasks/_helpers/sed.yml


        # Load the provided profile
        - name          : Loading Profile loading module
          include_tasks : tasks/_helpers/load-profile.yml
          vars:
            profile     : "{{ mymac_profile }}"
            append      : false
          when:
            - mymac_profile is defined
            - mymac_profile != ""


        # Fail if a profiles has not been set
        - name  : No profile provided; exiting
          fail:
            msg : "No profile provided; exiting."
          when  : not mymac_profile or mymac_profile == ""


    ### MODULES ######################################################################################################

    - name          : Loading MacOS module (1 / 6)
      include_tasks : tasks/macos.yml

    - name          : Loading Sudoers module (2 / 6)
      include_tasks : tasks/sudoers.yml

    - name          : Loading DevTools module (3 / 6)
      include_tasks : tasks/dev-tools.yml

    - name          : Loading Identity module (4 / 6)
      include_tasks : tasks/identity.yml

    - name          : Loading Time Machine module (5 / 6)
      include_tasks : tasks/time-machine.yml

    - name          : Loading App Store module (6 / 6)
      include_tasks : tasks/app-store.yml


    ### RESTART ######################################################################################################

    - block :

        - name : RESTARTING IN 10 SECONDS
          pause:
            seconds : 10

        - name   : RESTARTING
          become : true
          shell  : shutdown -r now

      when:
        - restart is defined
        - restart == true
