---
- hosts: local

  vars:
    scope : "{{ lookup('env', 'SCOPE') }}"

  tasks:

    # Check that this is a supported MacOS version (and computer)
    - name : Checking Operating system
      fail : msg="This installer is only supported by MacOSX, current operating system is \"{{ ansible_distribution }}\""
      when : ansible_distribution != "MacOSX"


    # # Check that the scope of the system has been set
    # - name : Checking for SCOPE environment variable
    #   fail : msg="Please set the environment variable SCOPE to either 'work' or 'personal'"
    #   when : scope != "work" and scope != "personal"
    #
    #
    # # Enable FileVault
    # - include : tasks/macos-filevault.yml
    #
    #
    # # Update any existing software before starting new paths
    # - include : tasks/macos-app-update.yml
    #   when    : false
    #
    #
    # # Create an ssh key in the user's home directory (if one does not already exist)
    # - include : tasks/create-ssh-key.yml
    #
    #
    # # Install XCode on the platform
    # - include : tasks/install-xcode.yml
    #
    #
    # # Install Homebrew
    # - include : tasks/install-homebrew.yml
    #
    #
    # # Install Homebrew packages
    # - include : tasks/install-homebrew-packages.yml
    #   vars:
    #     packages:
    #       - ack
    #       - bash-completion
    #       - dockutil
    #       - gettext
    #       - git
    #       - gpg
    #       - openssl
    #       - mcrypt
    #       - mysql
    #       - nmap
    #       - nvm
    #       - pv
    #       - ssh-copy-id
    #       - sqlite
    #       - unrar
    #       - watch
    #       - wget
    #
    #
    # Install common Homebrew casks
    - include: tasks/install-homebrew-casks.yml
      vars:
        taps:
          - caskroom/cask
          - caskroom/versions
        casks:
    #       - 1password
    #       - adobe-creative-cloud
    #       - adobe-photoshop-cc
          - atom
    #       - cloudapp
    #       - daisydisk
    #       - docker-toolbox
    #       - doxie
    #       - dropbox
    #       - evernote
    #       - filezilla
    #       - firefox
    #       - flash-player
    #       - flexiglass
    #       - google-chrome
    #       - google-drive
          - google-hangouts
    #       - intellij-idea-ce
    #       - istat-menus
    #       - java
    #       - skype
    #       - slack
    #       - snagit
    #       - spotify
    #       - the-unarchiver
    #       - unity-web-player
    #       - virtualbox
    #       - vlc
    #       - vlc-webplugin
    #
    #
    # # Install work Homebrew casks
    # - include : tasks/install-homebrew-casks.yml
    #   when    : scope == "work"
    #   vars:
    #     taps:
    #       - caskroom/cask
    #       - caskroom/versions
    #     casks:
    #       - ringcentral
    #       - tableau
    #       - tableau-reader
    #
    #
    # # Install personal Homebrew casks
    # - include : tasks/install-homebrew-casks.yml
    #   when    : scope == "personal"
    #   vars:
    #     taps:
    #       - caskroom/cask
    #       - caskroom/versions
    #     casks:
    #       - ableton-live-intro
    #       - arduino
    #       - beersmith2
    #       - handbrake
    #       - kicad
    #       - kicad-extras
    #       - kindle
    #       - league-of-legends
    #       - microsoft-office
    #       - nox-app-player
    #       - plex-media-player
    #       - steam
    #       - steamcmd
    #       - teamspeak-client
    #       - textual
    #       - transmission
    #       - unity
    #       - unity-android-support-for-editor
    #       - unity-download-assistant
    #       - unity-ios-support-for-editor
    #       - unity-linux-support-for-editor
    #       - unity-standard-assets
    #       - unity-webgl-support-for-editor
    #       - unity-windows-support-for-editor


    # Clean up the macOS Dock
    - include : tasks/macos-dock.yml
      vars:
        apps:
          - /Applications/Utilities/Terminal.app
          - /Applications/Google Chrome.app
          - /Applications/Atom.app
          - /Applications/Messages.app
          - /Applications/Slack.app
          - /Applications/Google Hangouts.app
          - /Applications/Spark.app
          - /Applications/Microsoft Outlook.app
          - /Applications/1Password 6.app
          - /Applications/Spotify.app
        spacers:
          - Atom
          - Google Hangouts
          - Microsoft Outlook


    - debug: msg="Installation has completed.  It is recommended that you restart the system to finalize the process."
