---
- hosts: local
  remote_user: root

  tasks:

      # Install XCode on the platform
      - include: tasks/install-xcode.yml

      # Install Homebrew
      - include: tasks/install-homebrew.yml

    
