---
- hosts: all
  connection: local

  vars:
    profile : "{{ lookup('env', 'PROFILE') }}"

  vars_files:
    - config.yml

  # Load whichever profile we want on top of the default
  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - "config.{{ profile }}.yml"
      tags : ['always']
      when : profile != ""

  tasks:

    # Helper task to set the proper path to sed
    - include : tasks/helpers/sed.yml

    # Configure sudoers on the system
    - include : tasks/sudoers.yml
      when    : sudoers is defined and sudoers != false and sudoers != []
