---
- hosts      : all
  connection : local

  roles:
    #- roliver.filevault
    - ansible-role-filevault

  # If a profile is provided, load it from the environment
  vars:
    mymac_profile : "{{ lookup('env', 'MYMAC_PROFILE')|default(omit) }}"


  # Run the profile
  tasks:

    ### PREP AND SETUP ###############################################################################################

    - name  : Setup
      block :

        # Check that our sudo password is correct
        - name         : Checking sudo password
          become       : true
          shell        : /usr/bin/true
          changed_when : false


        # Ensure we are running on macOS
        - name : Checking Operating System type
          fail : msg="This installer is only supported by MacOSX, current operating system is \"{{ ansible_distribution }}\""
          when : ansible_distribution != "MacOSX"


        # Helper tasks that provide shared functionality for modules
        - name          : Finding `sed` path
          include_tasks : tasks/helpers/sed.yml


        # If we have a profile set, load it
        - include_tasks : tasks/helpers/load-profile.yml
          vars:
            profile : "{{ mymac_profile }}"
            append  : false
          when:
            - mymac_profile is defined
            - mymac_profile != ""


        # Fail early if we don't have a profile
        - name : No profile provided; exiting
          fail : msg="No profile provided; exiting."
          when : not mymac_profile or mymac_profile == ""


    ### MODULES ######################################################################################################

    - name          : Loading MacOS module (1 / 4)
      include_tasks : tasks/macos.yml

    - name          : Loading Sudoers module (2 / 4)
      include_tasks : tasks/sudoers.yml

    - name          : Loading Identity module (3 / 4)
      include_tasks : tasks/identity.yml

    - name          : Loading DevTools module (4 / 4)
      include_tasks : tasks/dev-tools.yml
