#
# Manages installation of items from the App Store.
#
# Variables:
#   - update_frequency - integer that determines how often, in days, to check for updates
#   - email - the email of the AppStore login
#   - password - the password for the AppStore login (use Ansible Vault to encrypt this)
#
---

- name : AppStore
  block:

    - name     : Setting frequency for automatic updates
      osx_defaults:
        domain : com.apple.SoftwareUpdate
        key    : ScheduleFrequency
        type   : int
        value  : "{{ app_store.update_frequency|default(1) }}"
      when:
        - app_store.update_frequency is defined
        - app_store.update_frequency > 0

  when:
    - app_store is defined
    - app_store != false
    - app_store != []
