#
# Installs and configures the following:
#
#   - Homebrew
#   - MAS Homebrew Package (to install XCode)
#   - XCode
#   - XCode Command Line Tools
#
# Variables (not a part of dev_tools - should be parallel)
#   - app_store
#       - email - the email for the Apple AppStore
#       - password - the password for the Apple AppStore
#
---
- name  : DevTools
  block :

    # Install Homebrew MAS to install XCode
    - name: Upgrading Homebrew and MAS to latest version(s)
      homebrew:
        name            : mas
        state           : latest
        update_homebrew : yes


    # Install XCode from the Mac AppStore
    - name          : Updating XCode to latest version
      include_tasks : installers/app-store.yml
      vars:
        email    : "{{ app_store.email|default('') }}"
        password : "{{ app_store.password|default('') }}"
        apps:
          - { id: '497799835', name: 'Xcode (9.2)' }


    # Repeat installation checks until installation is complete
    - name          : Installing XCode Command Line Tools (Please accept any popup dialogs)
      become        : yes
      shell         : xcode-select --install
      register      : xcode_clt
      retries       : 400
      delay         : 15
      until         : xcode_clt.stderr.find("command line tools are already installed") != -1
      changed_when  : xcode_clt.attempts is defined and xcode_clt.attempts > 0
      failed_when   : xcode_clt.stderr.find("command line tools are already installed") == -1
      ignore_errors : true


    # Mark this script complete in case others need to reference it
    - name: Done
      set_fact:
        mymac: "{{ mymac|default([]) + [{ 'dev_tools': true }] }}"


  when:
    - dev_tools is defined
    - dev_tools != false
    - dev_tools != []
