#
# Configures identity and encryption on the system for the current user.
#
# Options:
#   - names
#       - computer - the name of this computer when used on the network, etc
#       - host - the hostname for the computer (without a .local suffix)
#   - ssh_key
#       - bits - how many bits to use for the SSH key (defaults to 4096)
#       - comment - the comment to include with the SSH key (defaults to user@hostname)
#       - password - the SSH key password (default none)
#   - gpg_key
#       - id - the ID of the key
#       - files
#           - private_key - the location of the private key file, as exported by gpg
#           - public_key - the location of the public key file, as exported by gpg
#
---
- name  : Identity
  block :

    # Names
    - name          : Loading Hostnames sub-module
      include_tasks : identity/hostnames.yml
      when :
        - identity.names is defined
        - identity.names.host is defined
        - identity.names.host != ""

    - name          : Loading Computer Identity sub-module
      include_tasks : identity/computer.yml
      when :
        - identity.names is defined
        - identity.names.computer is defined
        - identity.names.computer != ""


    # Flush the cache to apply any changes
    - name         : Flushing DNS cache
      become       : true
      shell        : dscacheutil -flushcache
      changed_when : false


    # Keys
    - name          : Loading SSH Key sub-module
      include_tasks : identity/ssh-key.yml
      when :
        - identity.ssh_key is defined
        - identity.ssh_key != false


    - name          : Loading GPG Key sub-module
      include_tasks : identity/gpg-key.yml
      when :
        - identity.gpg_key is defined
        - identity.gpg_key != false
        - identity.gpg_key.id is defined
        - identity.gpg_key.id != false
        - identity.gpg_key.id != ""
        - identity.gpg_key.files is defined
        - identity.gpg_key.files.public_key is defined
        - identity.gpg_key.files.public_key != false
        - identity.gpg_key.files.public_key != ""
        - identity.gpg_key.files.private_key is defined
        - identity.gpg_key.files.private_key != false
        - identity.gpg_key.files.private_key != ""


    # Mark this script complete in case others need to reference it
    - name     : Done
      set_fact :
        mymac  : "{{ mymac|default([]) + [{ 'identity': true }] }}"


  when:
    - identity is defined
    - identity != false
    - identity != []
