# Sets the computer's name, hostname, and other settings.  Should not be used on work computers.
---
#   pause :
#     msg      : "What is your name?"
#     register : user_name
# #
# - name    : "user_email"
#   prompt  : "What is your email?"
#   default : "hello@andrewvaughan.io"
#
# - name    : "computer_name"
#   prompt  : "What is this computer's host-friendly name?"
#   default : "{{ ansible_host }}"xw


# sudo scutil --set ComputerName "${NAME}'s MacBook"
# sudo scutil --set HostName "${HOST}"
# sudo scutil --set LocalHostName "${HOST}"
# sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string "${HOST}"
# sudo defaults write /Library/Preferences/com.apple.loginwindow LoginwindowText "If found, contact ${EMAIL}"
