# Configures the sudoers file on the system.
---

- name: Configuring sudoers
  become: yes
  template:
    src      : templates/private/etc/sudoers.d/mymac.j2
    dest     : /private/etc/sudoers.d/mymac
    mode     : 0440
    validate : 'visudo -cf %s'
  tags: [print_action]

- debug:
    msg       : Sudoer configuration complete. Created and validated /private/etc/sudoers.d/mymac from templates/private/etc/sudoers.d/mymac.j2
    verbosity : 2
