#
# Configures Time Machine backups
#
# Variables:
#   - connection_prompts - whether to give users prompts to make disks Time Machine backups when connected (default true)
#   - backup_interval - the time, in seconds, to wait between backups (default 3600, or 1 hour)
#   - volumes - a list of Volumes, already mounted, to use as backup destinations
#   - exclude - a list of files and/or directories to exclude from backups with Time Machine
---
- name : Time Machine
  block:

    - name         : Enabling Time Machine
      become       : true
      shell        : tmutil enable
      changed_when : false

    - name     : Setting new-disk connection prompts
      osx_defaults:
        domain : com.apple.TimeMachine
        key    : DoNotOfferNewDisksForBackup
        type   : boolean
        value  : "{{ time_machine.connection_prompts|default(true) == false }}"

    - name         : Checking System Integrity Protection status
      shell        : csrutil status
      changed_when : false
      register     : sip_status

    - debug:
        msg : WARNING - Could not set Time Machine Backup interval; System Integrity Protection is enabled
      when:
        - sip_status.stdout.find("enabled") != -1

    - name     : Setting Time Machine backup interval
      become   : true
      osx_defaults:
        domain : /System/Library/LaunchDaemons/com.apple.backupd-auto
        key    : StartInterval
        type   : int
        value  : "{{ time_machine.backup_interval|default(3600) }}"
      when:
        - sip_status.stdout.find("disabled") != -1

    - name         : Gathering target volume information
      shell        : tmutil destinationinfo
      register     : tm_destinations
      changed_when : false

    - name   : Configuring Time Machine Volumes
      become : true
      shell  : "tmutil setdestination -a \"{{ item }}\""
      with_items : "{{ time_machine.volumes }}"
      when:
        - time_machine.volumes is defined
        - time_machine.volumes != false
        - time_machine.volumes != []
        - item not in tm_destinations.stdout

    - include_tasks : "helpers/time-machine-exclusion.yml exclude={{ item }}"
      with_items    : "{{ time_machine.exclude }}"
      when:
        - time_machine.exclude is defined
        - time_machine.exclude != false
        - time_machine.exclude != []


  when:
    - time_machine is defined
    - time_machine != false
    - time_machine != []


# If set to false, disable Time Machine
- name : Time Machine
  block:

    - name         : Disabling Time Machine
      become       : true
      shell        : tmutil disable
      changed_when : false

  when:
    - time_machine is defined
    - time_machine == false
