# Loads a provided profile from either a file or a URL given a "profile" variable.
#
# Options:
#   - profile : the URL or file to load
#   - append  : prevents clearing of profile variables when set to `true`
---
- name  : Load Profile
  block :

    - fail : msg="No profile provided"
      when : profile is undefined or not profile or profile == ''

    - debug :
        msg       : "Loading profile '{{ profile }}'"
        verbosity : 1


    # Clear out to no-op settings unless `append` is set to true
    - name         : Clearing variables
      include_vars : profiles/noop.yml
      when         : append is undefined or not append


    # Use a file profile if provided a filename
    - name          : "Loading profile from {{ profile }}"
      include_vars  : "{{ profile }}"
      when          : "profile[0:4] != 'http'"


    # Load a URL, if provided one
    - name  : Via URL
      block :

        - name     : Reserving temporary file for download
          tempfile:
            state  : file
            prefix : mymac.
            suffix : .yml
          register : temp_profile

        - name    : "Downloading profile from {{ profile }}"
          get_url:
            url   : "{{ profile }}"
            dest  : "{{ temp_profile.path }}"
            force : true
          register : file

        - name         : Loading profile from downloaded file
          include_vars : "{{ temp_profile.path }}"

      when : "profile[0:4] == 'http'"


    # Output all variables currently set on max verbosity
    - debug :
        var       : hostvars
        verbosity : 2


    # Done!
    - name  : Done
      debug :
        msg       : "Profile loading complete"
        verbosity : 1
