#
# Configures the system's SSH key.
#
---
- name  : SSH Key
  block :

    - name : "Generating SSH key for user {{ ansible_user_id }}"
      user :
        name               : "{{ ansible_user_id }}"
        ssh_key_bits       : "{{ identity.ssh_key.bits|default(4096) }}"
        ssh_key_comment    : "{{ identity.ssh_key.comment|default(omit) }}"
        ssh_key_passphrase : "{{ identity.ssh_key.password|default(omit) }}"
        generate_ssh_key   : yes
