#
# Configures various configuration dotfiles on the system
#
---
- name  : Home Files
  block :

    - name : Copying files to home directory
      copy :
        src     : "{{ item }}"
        dest    : "~/{{ item|basename }}"
      with_items : "{{ macos.home_files }}"
      when :
        - macos.home_files is defined
        - macos.home_files != false
        - macos.home_files != []


    - name  : .bash_profile
      block :

        - name           : Adding exports and aliases
          blockinfile:
            path         : ~/.bash_profile
            create       : yes
            follow       : yes
            marker       : "### {mark} MYMAC MANAGED - MacOS MODULE"
            backup       : yes
            block        : "{{ lookup('template', 'templates/.bash_profile.j2') }}"
          register : bash_profile

        - name  : Sourcing .bash_profile
          shell : source ~/.bash_profile
          when  : bash_profile is changed

      when :
        - macos.bash_profile is defined
        - macos.bash_profile != false
        - macos.bash_profile != []
