#
# Configures miscellaneous system options
#
---
- name  : System
  block :

    - name  : Screenshots
      block :

        - name     : Setting file format
          osx_defaults :
            domain : com.apple.screencapture
            key    : type
            type   : string
            value  : "{{ macos.system.screenshots.type }}"
          when :
            - macos.system.screenshots.type is defined
            - macos.system.screenshots.type != false
            - macos.system.screenshots.type != ""


        - name     : Setting storage location
          osx_defaults :
            domain : com.apple.screencapture
            key    : location
            type   : string
            value  : "{{ macos.system.screenshots.location }}"
          when :
            - macos.system.screenshots.location is defined
            - macos.system.screenshots.location != false
            - macos.system.screenshots.location != ""

      when :
        - macos.system.screenshots is defined
        - macos.system.screenshots != false
        - macos.system.screenshots != []
