#
# Configures miscellaneous system options
#
---
- name  : System
  block :

    - name  : Battery
      block :

        - name     : Setting percentage visibility in menu
          osx_defaults :
            domain : com.apple.menuextra.battery
            key    : ShowPercent
            type   : string
            value  : "{{ 'YES' if macos.system.battery.show_percent == true else 'NO' }}"
          when :
            - macos.system.battery.show_percent is defined


        - name     : Setting time visibility in menu
          osx_defaults :
            domain : com.apple.menuextra.battery
            key    : ShowTime
            type   : string
            value  : "{{ 'YES' if macos.system.battery.show_time == true else 'NO' }}"
          when :
            - macos.system.battery.show_time is defined

      when :
        - macos.system.battery is defined
        - macos.system.battery != false
        - macos.system.battery != []


    - name  : Screenshots
      block :

        - name     : Setting file format
          osx_defaults :
            domain : com.apple.screencapture
            key    : type
            type   : string
            value  : "{{ macos.system.screenshots.type }}"
          when :
            - macos.system.screenshots.type is defined
            - macos.system.screenshots.type != false
            - macos.system.screenshots.type != ""


        - name     : Setting storage location
          osx_defaults :
            domain : com.apple.screencapture
            key    : location
            type   : string
            value  : "{{ macos.system.screenshots.location }}"
          when :
            - macos.system.screenshots.location is defined
            - macos.system.screenshots.location != false
            - macos.system.screenshots.location != ""

      when :
        - macos.system.screenshots is defined
        - macos.system.screenshots != false
        - macos.system.screenshots != []
