#
# Installs Mac AppStore applications using the Homebrew MAS tool.
#
# Required Variables:
#   email        : the email account to sign into the Mac AppStore with (optional)
#   password     : the password for the Mac AppStore account (optional)
#   upgrade_apps : set to true to upgrade existing AppStore applications
#   apps         : a list of apps to install in the following format:
#     - { id : "App Name (0.0)" }
#
# To list apps on your system on CLI:
#   mas list
#
# To get the ID of an application on CLI:
#   mas search "[App Name]"
#
---

- name  : AppStore
  block :

    # Make sure Homebrew is installed
    - name          : Loading Homebrew Installer sub-module
      include_tasks : manual/homebrew.yml


    # Ensure MAS is installed from Homebrew before continuing
    - name    : Checking prerequisites
      homebrew :
        name  : mas
        state : present
      when : >
        macos.devtools is not defined or
        not macos.devtools


    # Check if we're already logged in
    - name         : Checking authentication
      shell        : 'mas account'
      register     : mas_account_result
      failed_when  : mas_account_result.rc > 1
      changed_when : false


    # Attempt to login to the AppStore, if needed
    - block:

        - name     : Attempting sign-in
          shell    : 'mas signin "{{ email }}" "{{ password }}"'
          register : mas_signin_result
          when:
            - email is defined
            - email != ''
            - password is defined
            - password != ''


        - name     : Attempting Apple AppStore login using dialog and two-factor authentication
          shell    : 'mas signin "{{ email }}" "{{ password }}" --dialog'
          register : mas_signin_result
          when:
            - mas_signin_result.skipped or mas_signin_result.failed

      when:
        - mas_account_result.rc != 0


    # Load any existing apps (if apps list set)
    - block:

        - name         : Loading currently installed Apple AppStore application(s)
          command      : 'mas list'
          register     : mas_list
          when         : apps is defined
          check_mode   : no
          changed_when : false


        # Install the applications listed (if apps list set)
        - name       : Installing application(s) not currently installed in Apple AppStore
          command    : "mas install {{ item.id }}"
          with_items : "{{ apps }}"
          when :
            - apps is defined
            - mas_list is defined
            - mas_list.stdout is defined
            - item.id not in mas_list.stdout


        # Upgrade all AppStore apps to their latest (if upgrade_apps set)
        - name    : Upgrading existing Apple AppStore application(s)
          command : mas upgrade
          when :
            - upgrade_apps is defined
            - upgrade_apps

      when:
        - (mas_account_result.result == 0) or
          (not mas_signin_result.skipped and mas_signin_result.rc == 0)
